;;; cache-e2e-scenarios.lisp
(defun slurp (p) (with-open-file (in p) (let ((s (make-string (file-length in)))) (read-sequence s in) s)))
(defvar *pass* 0) (defvar *fail* 0)
(defun pass (n) (incf *pass*) (format t "  PASS ~A~%" n))
(defun fail (n r) (incf *fail*) (format t "  FAIL ~A: ~A~%" n r))
(defun ac (c needle s) (if (search needle c :test #'char=) (pass s) (fail s (format nil "missing ~S" needle))))
(let ((c (slurp "/home/slime/projects/clpkg-cache-store/src/core/cache-types.coal")))
  (ac c "module Core.CacheTypes" "S1-module")
  (ac c "data EvictionPolicy" "S2") (ac c "data CacheEntry" "S3")
  (ac c "data CacheStats" "S4") (ac c "data CacheConfig" "S5")
  (ac c "data CacheOperation" "S6") (ac c "data CacheEvent" "S7")
  (ac c "data TtlPolicy" "S8") (ac c "data PartitionStrategy" "S9")
  (ac c "data CachePartition" "S10") (ac c "data SerializationFormat" "S11")
  (ac c "data WarmupSource" "S12") (ac c "data CacheHealth" "S13")
  (ac c "data CacheResult" "S14")
  (ac c "entry-expired-p" "S15") (ac c "hit-rate-pct" "S16")
  (ac c "cache-full-p" "S17") (ac c "partition-load-pct" "S18")
  (ac c "LRU" "S19") (ac c "LFU" "S20") (ac c "FIFO" "S21")
  (ac c "CacheHit" "S22") (ac c "CacheMiss" "S23") (ac c "CacheEviction" "S24")
  (ac c "FixedTtl" "S25") (ac c "SlidingTtl" "S26") (ac c "NoTtl" "S27")
  (ac c "HashPartition" "S28") (ac c "JsonSerialization" "S29")
  (ac c "FileWarmup" "S30") (ac c "Healthy" "S31") (ac c "Degraded" "S32")
  (ac c "CacheEntry -> Int -> Int -> Bool" "S33")
  (ac c "CacheStats -> Int" "S34")
  (ac c "CacheConfig -> Int -> Bool" "S35"))
(format t "~%=== E2E Results: ~D/~D PASSED ===~%" *pass* (+ *pass* *fail*))
(sb-ext:exit :code (if (zerop *fail*) 0 1))
