(load "packages/clpkg-shell/src/package.lisp")
(load "packages/clpkg-shell/src/model.lisp")
(load "packages/clpkg-shell/src/api.lisp")
(in-package #:clpkg-shell)

(defun %write-json (path json)
  (ensure-directories-exist path)
  (with-open-file (o path :direction :output :if-exists :supersede)
    (write-string json o)))
(defun %json-bool (x) (if x "true" "false"))

(let* ((sec-path "packages/clpkg-shell/artifacts/gates/security-gates.json")
       (perf-path "packages/clpkg-shell/artifacts/gates/perf-gates.json")
       (rel-path "packages/clpkg-shell/artifacts/gates/release-checks.json")
       (session (spawn-shell-session :cwd "/tmp" :shell "/bin/bash" :env-keys '("PATH")))
       (start (get-internal-real-time))
       (res (run-shell-command session "printf shell-ok"))
       (elapsed (* 1000.0d0 (/ (- (get-internal-real-time) start) internal-time-units-per-second)))
       (sec-ok (and (eq (ss-state session) :running) (string= (cr-stdout res) "shell-ok")))
       (perf-ok (< elapsed 120.0d0))
       (release-ok (and (probe-file "packages/clpkg-shell/clpkg-shell.asd")
                        (probe-file "packages/clpkg-shell/e2e/run-s1-s6.sh"))))
  (%write-json sec-path (format nil "{\"session_running\":~A,\"stdout_ok\":~A,\"pass\":~A}"
                                (%json-bool (eq (ss-state session) :running))
                                (%json-bool (string= (cr-stdout res) "shell-ok"))
                                (%json-bool sec-ok)))
  (%write-json perf-path (format nil "{\"elapsed_ms\":~,3f,\"budget_ms\":120.0,\"pass\":~A}"
                                 elapsed (%json-bool perf-ok)))
  (%write-json rel-path (format nil "{\"asd_present\":~A,\"e2e_script_present\":~A,\"pass\":~A}"
                                (%json-bool (not (null (probe-file "packages/clpkg-shell/clpkg-shell.asd"))))
                                (%json-bool (not (null (probe-file "packages/clpkg-shell/e2e/run-s1-s6.sh"))))
                                (%json-bool release-ok)))
  (unless (and sec-ok perf-ok release-ok)
    (error "shell gate verifier failed"))
  (format t "PASS shell security/performance/release checks~%"))
