;;; graph-e2e-scenarios.lisp
(defun slurp (p) (with-open-file (in p) (let ((s (make-string (file-length in)))) (read-sequence s in) s)))
(defvar *pass* 0) (defvar *fail* 0)
(defun pass (n) (incf *pass*) (format t "  PASS ~A~%" n))
(defun fail (n r) (incf *fail*) (format t "  FAIL ~A: ~A~%" n r))
(defun ac (c needle s) (if (search needle c :test #'char=) (pass s) (fail s (format nil "missing ~S" needle))))
(let ((c (slurp "/home/slime/projects/clpkg-graph-db/src/core/graph-types.coal")))
  (ac c "module Core.GraphTypes" "S1") (ac c "data PropertyValue" "S2")
  (ac c "data NodeLabel" "S3") (ac c "data GraphNode" "S4")
  (ac c "data EdgeType" "S5") (ac c "data GraphEdge" "S6")
  (ac c "data TraversalDirection" "S7") (ac c "data TraversalStep" "S8")
  (ac c "data PathResult" "S9") (ac c "data GraphPattern" "S10")
  (ac c "data MatchClause" "S11") (ac c "data GraphIndex" "S12")
  (ac c "data GraphTransaction" "S13") (ac c "data GraphConfig" "S14")
  (ac c "data GraphResult" "S15") (ac c "node-has-label" "S16")
  (ac c "edge-connects" "S17") (ac c "path-length" "S18")
  (ac c "pattern-node-count" "S19") (ac c "PropString" "S20")
  (ac c "PropInt" "S21") (ac c "PropBool" "S22") (ac c "PropNull" "S23")
  (ac c "Outgoing" "S24") (ac c "Incoming" "S25") (ac c "Both" "S26")
  (ac c "ExpandEdge" "S27") (ac c "FilterLabel" "S28") (ac c "LimitDepth" "S29")
  (ac c "NodePattern" "S30") (ac c "EdgePattern" "S31") (ac c "PathPattern" "S32")
  (ac c "LabelIndex" "S33") (ac c "FullTextIndex" "S34")
  (ac c "TxReadOnly" "S35") (ac c "TxBatch" "S36")
  (ac c "GraphNode -> NodeLabel -> Bool" "S37")
  (ac c "GraphEdge -> String -> String -> Bool" "S38")
  (ac c "PathResult -> Int" "S39"))
(format t "~%=== E2E Results: ~D/~D PASSED ===~%" *pass* (+ *pass* *fail*))
(sb-ext:exit :code (if (zerop *fail*) 0 1))
