(defun slurp (p) (with-open-file (in p) (let ((s (make-string (file-length in)))) (read-sequence s in) s)))
(defvar *pass* 0) (defvar *fail* 0)
(defun pass (n) (incf *pass*) (format t "  PASS ~A~%" n))
(defun fail (n r) (incf *fail*) (format t "  FAIL ~A: ~A~%" n r))
(defun ac (c needle s) (if (search needle c :test #'char=) (pass s) (fail s (format nil "missing ~S" needle))))
(let ((c (slurp "/home/slime/projects/clpkg-siem/src/core/siem-types.coal")))
  (ac c "module Core.SiemTypes" "S1") (ac c "data LogSource" "S2")
  (ac c "data LogSourceType" "S3") (ac c "data NormalizedEvent" "S4")
  (ac c "data EventCategory" "S5") (ac c "data DetectionRule" "S6")
  (ac c "data RuleLogic" "S7") (ac c "data AlertPriority" "S8")
  (ac c "data Alert" "S9") (ac c "data AlertStatus" "S10")
  (ac c "data CorrelationRule" "S11") (ac c "data Dashboard" "S12")
  (ac c "data DashboardWidget" "S13") (ac c "data WidgetType" "S14")
  (ac c "data SiemResult" "S15") (ac c "event-is-security" "S16")
  (ac c "alert-active-p" "S17") (ac c "rule-matches-category" "S18")
  (ac c "dashboard-widget-count" "S19") (ac c "Syslog" "S20")
  (ac c "CloudTrail" "S21") (ac c "Authentication" "S22")
  (ac c "MalwareDetection" "S23") (ac c "DataExfiltration" "S24")
  (ac c "PatternMatch" "S25") (ac c "Threshold" "S26") (ac c "Anomaly" "S27")
  (ac c "AlertNew" "S28") (ac c "AlertFalsePositive" "S29")
  (ac c "TimeSeriesChart" "S30") (ac c "PieChart" "S31")
  (ac c "NormalizedEvent -> Bool" "S32") (ac c "Alert -> Bool" "S33")
  (ac c "Dashboard -> Int" "S34"))
(format t "~%=== E2E Results: ~D/~D PASSED ===~%" *pass* (+ *pass* *fail*))
(sb-ext:exit :code (if (zerop *fail*) 0 1))
