(in-package #:clpkg-ssh-client)

(deftype connection-state () '(member :new :connecting :authenticated :closed :error))

(defstruct (host-profile (:conc-name hp-))
  (host "" :type string)
  (port 22 :type integer)
  (username "" :type string)
  (strict-host-key-p t :type boolean)
  (known-hosts-path "" :type string))

(defstruct (credential-profile (:conc-name cp-))
  (method :key :type keyword)
  (key-path "" :type string)
  (password-ref "" :type string)
  (agent-enabled-p t :type boolean))

(defstruct (ssh-session (:conc-name ssn-))
  (session-id "" :type string)
  (state :new :type connection-state)
  (host (make-host-profile) :type host-profile)
  (credential (make-credential-profile) :type credential-profile)
  (last-error "" :type string))

(defun build-session-summary (session)
  (declare (type ssh-session session)
           (optimize (safety 3)))
  (list :session-id (ssn-session-id session)
        :state (ssn-state session)
        :host (hp-host (ssn-host session))
        :port (hp-port (ssn-host session))
        :username (hp-username (ssn-host session))
        :strict-host-key (hp-strict-host-key-p (ssn-host session))
        :auth-method (cp-method (ssn-credential session))))
