;;; iac-e2e-scenarios.lisp — E2E scenario tests for IaC runner ADTs

(defun slurp (p) (with-open-file (in p) (let ((s (make-string (file-length in)))) (read-sequence s in) s)))
(defvar *pass* 0) (defvar *fail* 0)
(defun pass (n) (incf *pass*) (format t "  PASS ~A~%" n))
(defun fail (n r) (incf *fail*) (format t "  FAIL ~A: ~A~%" n r))
(defun ac (c needle s) (if (search needle c :test #'char=) (pass s) (fail s (format nil "missing ~S" needle))))

(let ((c (slurp "/home/slime/projects/clpkg-iac-runner/src/core/iac-types.coal")))
  (ac c "module Core.IacTypes" "S1-module")
  (ac c "data ResourceType" "S2-resource-type")
  (ac c "data ResourceState" "S3-resource-state")
  (ac c "data ResourceSpec" "S4-resource-spec")
  (ac c "data PlanActionType" "S5-plan-action-type")
  (ac c "data PlanAction" "S6-plan-action")
  (ac c "data ExecutionPlan" "S7-execution-plan")
  (ac c "data ApplyStatus" "S8-apply-status")
  (ac c "data ApplyResult" "S9-apply-result")
  (ac c "data DriftSeverity" "S10-drift-severity")
  (ac c "data DriftEntry" "S11-drift-entry")
  (ac c "data DriftReport" "S12-drift-report")
  (ac c "data ProviderType" "S13-provider-type")
  (ac c "data ProviderConfig" "S14-provider-config")
  (ac c "data StateBackend" "S15-state-backend")
  (ac c "data IacResult" "S16-iac-result")
  (ac c "resource-needs-update" "S17-resource-needs-update")
  (ac c "plan-action-count" "S18-plan-action-count")
  (ac c "drift-has-breaking" "S19-drift-has-breaking")
  (ac c "apply-succeeded-p" "S20-apply-succeeded-p")
  (ac c "Compute" "S21-compute-constructor")
  (ac c "ActionCreate" "S22-action-create")
  (ac c "ActionDelete" "S23-action-delete")
  (ac c "ApplySucceeded" "S24-apply-succeeded")
  (ac c "ApplyRolledBack" "S25-apply-rolled-back")
  (ac c "DriftCritical" "S26-drift-critical")
  (ac c "AwsProvider" "S27-aws-provider")
  (ac c "LocalStateFile" "S28-local-state-file")
  (ac c "ResourceState -> Bool" "S29-needs-update-sig")
  (ac c "ExecutionPlan -> Int" "S30-plan-count-sig")
  (ac c "DriftReport -> Bool" "S31-drift-breaking-sig")
  (ac c "ApplyResult -> Bool" "S32-apply-success-sig"))

(format t "~%=== E2E Results: ~D/~D PASSED ===~%" *pass* (+ *pass* *fail*))
(sb-ext:exit :code (if (zerop *fail*) 0 1))
