(defun slurp (p) (with-open-file (in p) (let ((s (make-string (file-length in)))) (read-sequence s in) s)))
(defvar *pass* 0) (defvar *fail* 0)
(defun pass (n) (incf *pass*) (format t "  PASS ~A~%" n))
(defun fail (n r) (incf *fail*) (format t "  FAIL ~A: ~A~%" n r))
(defun ac (c needle s) (if (search needle c :test #'char=) (pass s) (fail s (format nil "missing ~S" needle))))
(let ((c (slurp "/home/slime/projects/clpkg-doc-db/src/core/doc-types.coal")))
  (ac c "module Core.DocTypes" "S1") (ac c "data JsonValue" "S2")
  (ac c "data Document" "S3") (ac c "data Collection" "S4")
  (ac c "data DocQuery" "S5") (ac c "data QueryOperator" "S6")
  (ac c "data SortOrder" "S7") (ac c "data SortField" "S8")
  (ac c "data Projection" "S9") (ac c "data DocIndex" "S10")
  (ac c "data IndexType" "S11") (ac c "data WriteResult" "S12")
  (ac c "data BulkOperation" "S13") (ac c "data ChangeEvent" "S14")
  (ac c "data DocResult" "S15") (ac c "document-has-field" "S16")
  (ac c "collection-count" "S17") (ac c "query-has-filter" "S18")
  (ac c "sort-ascending-p" "S19") (ac c "JString" "S20") (ac c "JNull" "S21")
  (ac c "JArray" "S22") (ac c "JObject" "S23") (ac c "Eq" "S24")
  (ac c "Regex" "S25") (ac c "And" "S26") (ac c "Or" "S27")
  (ac c "Include" "S28") (ac c "Exclude" "S29") (ac c "TextIndex" "S30")
  (ac c "GeoSpatial" "S31") (ac c "InsertResult" "S32") (ac c "UpsertResult" "S33")
  (ac c "BulkInsert" "S34") (ac c "InsertEvent" "S35")
  (ac c "Document -> String -> Bool" "S36") (ac c "Collection -> Int" "S37")
  (ac c "SortField -> Bool" "S38"))
(format t "~%=== E2E Results: ~D/~D PASSED ===~%" *pass* (+ *pass* *fail*))
(sb-ext:exit :code (if (zerop *fail*) 0 1))
