;;; obs-e2e-scenarios.lisp — E2E for observability ADTs

(defun slurp (p) (with-open-file (in p) (let ((s (make-string (file-length in)))) (read-sequence s in) s)))
(defvar *pass* 0) (defvar *fail* 0)
(defun pass (n) (incf *pass*) (format t "  PASS ~A~%" n))
(defun fail (n r) (incf *fail*) (format t "  FAIL ~A: ~A~%" n r))
(defun ac (c needle s) (if (search needle c :test #'char=) (pass s) (fail s (format nil "missing ~S" needle))))

(let ((c (slurp "/home/slime/projects/clpkg-observability/src/core/obs-types.coal")))
  (ac c "module Core.ObsTypes" "S1-module")
  (ac c "data MetricType" "S2-metric-type")
  (ac c "data MetricUnit" "S3-metric-unit")
  (ac c "data Metric" "S4-metric")
  (ac c "data MetricPoint" "S5-metric-point")
  (ac c "data SpanStatus" "S6-span-status")
  (ac c "data SpanContext" "S7-span-context")
  (ac c "data Span" "S8-span")
  (ac c "data LogLevel" "S9-log-level")
  (ac c "data LogEntry" "S10-log-entry")
  (ac c "data HealthStatus" "S11-health-status")
  (ac c "data HealthCheck" "S12-health-check")
  (ac c "data AlertSeverity" "S13-alert-severity")
  (ac c "data AlertState" "S14-alert-state")
  (ac c "data AlertRule" "S15-alert-rule")
  (ac c "data ObsResult" "S16-obs-result")
  (ac c "metric-is-counter" "S17-metric-is-counter")
  (ac c "span-duration-ms" "S18-span-duration-ms")
  (ac c "log-level-rank" "S19-log-level-rank")
  (ac c "health-ok-p" "S20-health-ok-p")
  (ac c "alert-firing-p" "S21-alert-firing-p")
  (ac c "Counter" "S22-counter")
  (ac c "Gauge" "S23-gauge")
  (ac c "Histogram" "S24-histogram")
  (ac c "Metric -> Bool" "S25-metric-counter-sig")
  (ac c "Span -> Int" "S26-span-duration-sig")
  (ac c "LogLevel -> Int" "S27-log-rank-sig")
  (ac c "HealthCheck -> Bool" "S28-health-ok-sig")
  (ac c "AlertRule -> Bool" "S29-alert-firing-sig"))

(format t "~%=== E2E Results: ~D/~D PASSED ===~%" *pass* (+ *pass* *fail*))
(sb-ext:exit :code (if (zerop *fail*) 0 1))
