(defun slurp (p) (with-open-file (in p) (let ((s (make-string (file-length in)))) (read-sequence s in) s)))
(defvar *p* 0) (defvar *f* 0)
(defun p (n) (incf *p*) (format t "  PASS ~A~%" n))
(defun f (n r) (incf *f*) (format t "  FAIL ~A: ~A~%" n r))
(defun a (c n s) (if (search n c :test #'char=) (p s) (f s (format nil "~S" n))))
(let ((c (slurp "/home/slime/projects/clpkg-vpn-client/src/core/vpn-types.coal")))
  (a c "module Core.VpnTypes" "S1") (a c "data VpnProtocol" "S2")
  (a c "data TunnelState" "S3") (a c "data VpnConfig" "S4")
  (a c "data Endpoint" "S5") (a c "data Certificate" "S6")
  (a c "data CertStatus" "S7") (a c "data DnsConfig" "S8")
  (a c "data SplitTunnelRule" "S9") (a c "data SplitTunnelMode" "S10")
  (a c "data ConnectionStats" "S11") (a c "data VpnProfile" "S12")
  (a c "data KillSwitchMode" "S13") (a c "data VpnEvent" "S14")
  (a c "data VpnResult" "S15") (a c "tunnel-connected-p" "S16")
  (a c "cert-valid-p" "S17") (a c "connection-uptime-secs" "S18")
  (a c "kill-switch-active-p" "S19") (a c "WireGuard" "S20")
  (a c "OpenVPN" "S21") (a c "IPSec" "S22") (a c "Connected" "S23")
  (a c "CertValid" "S24") (a c "CertExpired" "S25") (a c "AllTraffic" "S26")
  (a c "KillSwitchOn" "S27") (a c "TunnelState -> Bool" "S28")
  (a c "Certificate -> Bool" "S29") (a c "KillSwitchMode -> Bool" "S30"))
(format t "~%=== E2E: ~D/~D PASSED ===~%" *p* (+ *p* *f*))
(sb-ext:exit :code (if (zerop *f*) 0 1))
