(defun slurp (p) (with-open-file (in p) (let ((s (make-string (file-length in)))) (read-sequence s in) s)))
(defvar *p* 0) (defvar *f* 0)
(defun p (n) (incf *p*) (format t "  PASS ~A~%" n))
(defun f (n r) (incf *f*) (format t "  FAIL ~A: ~A~%" n r))
(defun a (c n s) (if (search n c :test #'char=) (p s) (f s (format nil "~S" n))))
(let ((c (slurp "/home/slime/projects/clpkg-firewall/src/core/firewall-types.coal")))
  (a c "module Core.FirewallTypes" "S1") (a c "data Protocol" "S2")
  (a c "data PortRange" "S3") (a c "data RuleAction" "S4")
  (a c "data RuleDirection" "S5") (a c "data FirewallRule" "S6")
  (a c "data RuleChain" "S7") (a c "data ChainPolicy" "S8")
  (a c "data Zone" "S9") (a c "data NatType" "S10")
  (a c "data NatRule" "S11") (a c "data RateLimitRule" "S12")
  (a c "data ConnectionState" "S13") (a c "data FirewallConfig" "S14")
  (a c "data FirewallResult" "S15") (a c "rule-permits-p" "S16")
  (a c "chain-rule-count" "S17") (a c "nat-is-snat" "S18")
  (a c "port-in-range" "S19") (a c "Allow" "S20") (a c "Deny" "S21")
  (a c "Drop" "S22") (a c "Inbound" "S23") (a c "Forward" "S24")
  (a c "SNAT" "S25") (a c "DNAT" "S26") (a c "Masquerade" "S27")
  (a c "Established" "S28") (a c "FirewallRule -> Bool" "S29")
  (a c "PortRange -> Int -> Bool" "S30"))
(format t "~%=== E2E: ~D/~D PASSED ===~%" *p* (+ *p* *f*))
(sb-ext:exit :code (if (zerop *f*) 0 1))
