;;; tsdb-e2e-scenarios.lisp
(defun slurp (p) (with-open-file (in p) (let ((s (make-string (file-length in)))) (read-sequence s in) s)))
(defvar *pass* 0) (defvar *fail* 0)
(defun pass (n) (incf *pass*) (format t "  PASS ~A~%" n))
(defun fail (n r) (incf *fail*) (format t "  FAIL ~A: ~A~%" n r))
(defun ac (c needle s) (if (search needle c :test #'char=) (pass s) (fail s (format nil "missing ~S" needle))))
(let ((c (slurp "/home/slime/projects/clpkg-tsdb/src/core/tsdb-types.coal")))
  (ac c "module Core.TsdbTypes" "S1") (ac c "data TimeResolution" "S2")
  (ac c "data DataPoint" "S3") (ac c "data TimeSeries" "S4")
  (ac c "data AggregateFunction" "S5") (ac c "data AggregateResult" "S6")
  (ac c "data RetentionTier" "S7") (ac c "data DownsamplePolicy" "S8")
  (ac c "data QueryRange" "S9") (ac c "data TsQuery" "S10")
  (ac c "data WriteBuffer" "S11") (ac c "data CompactionState" "S12")
  (ac c "data ShardKey" "S13") (ac c "data TsdbConfig" "S14")
  (ac c "data TsdbResult" "S15") (ac c "datapoint-in-range" "S16")
  (ac c "series-point-count" "S17") (ac c "retention-expired-p" "S18")
  (ac c "buffer-full-p" "S19") (ac c "Nanosecond" "S20") (ac c "Millisecond" "S21")
  (ac c "Sum" "S22") (ac c "Avg" "S23") (ac c "Percentile" "S24") (ac c "Rate" "S25")
  (ac c "CompactionIdle" "S26") (ac c "CompactionRunning" "S27")
  (ac c "TimeShard" "S28") (ac c "HashShard" "S29")
  (ac c "DataPoint -> Int -> Int -> Bool" "S30")
  (ac c "TimeSeries -> Int" "S31") (ac c "RetentionTier -> Int -> Bool" "S32")
  (ac c "WriteBuffer -> Bool" "S33"))
(format t "~%=== E2E Results: ~D/~D PASSED ===~%" *pass* (+ *pass* *fail*))
(sb-ext:exit :code (if (zerop *fail*) 0 1))
