(in-package #:clpkg-clipboard-history)

(defun append-entry (store entry)
  (declare (type clipboard-store store)
           (type clipboard-entry entry)
           (optimize (safety 3)))
  (let* ((entries (cons entry (cs-entries store)))
         (trimmed (subseq entries 0 (min (length entries) (cs-limit store)))))
    (make-clipboard-store :limit (cs-limit store) :entries trimmed)))

(defun store->newest-first (store)
  (declare (type clipboard-store store) (optimize (safety 3)))
  (sort (copy-list (cs-entries store))
        (lambda (a b)
          (declare (type clipboard-entry a b))
          (> (ce-created-at a) (ce-created-at b)))))

(defun query-substring (store needle)
  (declare (type clipboard-store store)
           (type string needle)
           (optimize (safety 3)))
  (remove-if-not (lambda (e)
                   (declare (type clipboard-entry e))
                   (search needle (ce-text e)))
                 (store->newest-first store)))
