;;; cost-e2e-scenarios.lisp — E2E for cost dashboard ADTs

(defun slurp (p) (with-open-file (in p) (let ((s (make-string (file-length in)))) (read-sequence s in) s)))
(defvar *pass* 0) (defvar *fail* 0)
(defun pass (n) (incf *pass*) (format t "  PASS ~A~%" n))
(defun fail (n r) (incf *fail*) (format t "  FAIL ~A: ~A~%" n r))
(defun ac (c needle s) (if (search needle c :test #'char=) (pass s) (fail s (format nil "missing ~S" needle))))

(let ((c (slurp "/home/slime/projects/clpkg-cost-dashboard/src/core/cost-types.coal")))
  (ac c "module Core.CostTypes" "S1-module")
  (ac c "data Currency" "S2-currency")
  (ac c "data MoneyAmount" "S3-money-amount")
  (ac c "data BillingPeriod" "S4-billing-period")
  (ac c "data ResourceTag" "S5-resource-tag")
  (ac c "data SpendEntry" "S6-spend-entry")
  (ac c "data Budget" "S7-budget")
  (ac c "data BudgetStatus" "S8-budget-status")
  (ac c "data ForecastMethod" "S9-forecast-method")
  (ac c "data CostForecast" "S10-cost-forecast")
  (ac c "data AlertAction" "S11-alert-action")
  (ac c "data AlertThreshold" "S12-alert-threshold")
  (ac c "data CostReport" "S13-cost-report")
  (ac c "data CostResult" "S14-cost-result")
  (ac c "money-to-cents" "S15-money-to-cents")
  (ac c "budget-remaining-pct" "S16-budget-remaining-pct")
  (ac c "spend-total-cents" "S17-spend-total-cents")
  (ac c "threshold-exceeded-p" "S18-threshold-exceeded-p")
  (ac c "USD" "S19-usd")
  (ac c "EUR" "S20-eur")
  (ac c "MoneyAmount -> Int" "S21-money-cents-sig")
  (ac c "Budget -> Int" "S22-budget-remaining-sig")
  (ac c "AlertThreshold -> Budget -> Bool" "S23-threshold-sig"))

(format t "~%=== E2E Results: ~D/~D PASSED ===~%" *pass* (+ *pass* *fail*))
(sb-ext:exit :code (if (zerop *fail*) 0 1))
