(defpackage #:clpkg-plain-text-editor
  (:use #:cl)
  (:export
   #:plaintext-config
   #:make-plaintext-config
   #:plaintext-config-root
   #:plaintext-config-encoding
   #:text-buffer-snapshot
   #:make-text-buffer-snapshot
   #:text-buffer-snapshot-path
   #:text-buffer-snapshot-content
   #:text-edit-op
   #:make-text-edit-op
   #:text-edit-op-start
   #:text-edit-op-end
   #:text-edit-op-replacement
   #:search-result
   #:make-search-result
   #:search-result-start
   #:search-result-end
   #:search-result-snippet
   #:text-diagnostic
   #:make-text-diagnostic
   #:text-diagnostic-code
   #:text-diagnostic-message
   #:text-diagnostic-severity
   #:text-diagnostic-offset
   #:plaintext-report
   #:make-plaintext-report
   #:plaintext-report-checks
   #:plaintext-report-summary
   #:open-buffer
   #:save-buffer
   #:apply-edit
   #:search-buffer
   #:validate-buffer
   #:generate-report))
