(defun slurp (p) (with-open-file (in p) (let ((s (make-string (file-length in)))) (read-sequence s in) s)))
(defvar *p* 0) (defvar *f* 0)
(defun p (n) (incf *p*) (format t "  PASS ~A~%" n))
(defun f (n r) (incf *f*) (format t "  FAIL ~A: ~A~%" n r))
(defun a (c n s) (if (search n c :test #'char=) (p s) (f s (format nil "~S" n))))
(let ((c (slurp "/home/slime/projects/clpkg-vuln-scanner/src/core/vuln-types.coal")))
  (a c "module Core.VulnTypes" "S1") (a c "data VulnSeverity" "S2")
  (a c "data CvssScore" "S3") (a c "data Vulnerability" "S4")
  (a c "data ScanTarget" "S5") (a c "data TargetType" "S6")
  (a c "data ScanPolicy" "S7") (a c "data ScanStatus" "S8")
  (a c "data ScanResult" "S9") (a c "data Finding" "S10")
  (a c "data Remediation" "S11") (a c "data RemediationPriority" "S12")
  (a c "data ComplianceCheck" "S13") (a c "data ComplianceStatus" "S14")
  (a c "data VulnResult" "S15") (a c "vuln-is-critical" "S16")
  (a c "scan-complete-p" "S17") (a c "finding-count" "S18")
  (a c "remediation-overdue-p" "S19") (a c "VulnCritical" "S20")
  (a c "Host" "S21") (a c "WebApp" "S22") (a c "SourceCode" "S23")
  (a c "ScanQueued" "S24") (a c "ScanComplete" "S25")
  (a c "RemImmediate" "S26") (a c "Compliant" "S27") (a c "NonCompliant" "S28")
  (a c "Vulnerability -> Bool" "S29") (a c "ScanStatus -> Bool" "S30"))
(format t "~%=== E2E: ~D/~D PASSED ===~%" *p* (+ *p* *f*))
(sb-ext:exit :code (if (zerop *f*) 0 1))
