;;; gateway-e2e-scenarios.lisp — E2E for API gateway ADTs

(defun slurp (p) (with-open-file (in p) (let ((s (make-string (file-length in)))) (read-sequence s in) s)))
(defvar *pass* 0) (defvar *fail* 0)
(defun pass (n) (incf *pass*) (format t "  PASS ~A~%" n))
(defun fail (n r) (incf *fail*) (format t "  FAIL ~A: ~A~%" n r))
(defun ac (c needle s) (if (search needle c :test #'char=) (pass s) (fail s (format nil "missing ~S" needle))))

(let ((c (slurp "/home/slime/projects/clpkg-api-gateway/src/core/gateway-types.coal")))
  (ac c "module Core.GatewayTypes" "S1-module")
  (ac c "data HttpMethod" "S2-http-method")
  (ac c "data Route" "S3-route")
  (ac c "data RouteMatch" "S4-route-match")
  (ac c "data RateLimitWindow" "S5-rate-limit-window")
  (ac c "data RateLimiter" "S6-rate-limiter")
  (ac c "data AuthType" "S7-auth-type")
  (ac c "data AuthPolicy" "S8-auth-policy")
  (ac c "data TransformOp" "S9-transform-op")
  (ac c "data RequestTransform" "S10-request-transform")
  (ac c "data ResponseTransform" "S11-response-transform")
  (ac c "data UpstreamTarget" "S12-upstream-target")
  (ac c "data Upstream" "S13-upstream")
  (ac c "data CorsConfig" "S14-cors-config")
  (ac c "data GatewayConfig" "S15-gateway-config")
  (ac c "data GatewayResult" "S16-gateway-result")
  (ac c "route-matches-method" "S17-route-matches-method")
  (ac c "rate-limit-exceeded-p" "S18-rate-limit-exceeded-p")
  (ac c "auth-required-p" "S19-auth-required-p")
  (ac c "upstream-healthy-count" "S20-upstream-healthy-count")
  (ac c "ExactMatch" "S21-exact-match")
  (ac c "PrefixMatch" "S22-prefix-match")
  (ac c "RegexMatch" "S23-regex-match")
  (ac c "JwtAuth" "S24-jwt-auth")
  (ac c "ApiKeyAuth" "S25-api-key-auth")
  (ac c "OAuth2" "S26-oauth2")
  (ac c "AddHeader" "S27-add-header")
  (ac c "RewritePath" "S28-rewrite-path")
  (ac c "PerSecond" "S29-per-second")
  (ac c "Route -> HttpMethod -> Bool" "S30-route-matches-sig")
  (ac c "RateLimiter -> Int -> Bool" "S31-rate-limit-sig")
  (ac c "AuthPolicy -> Bool" "S32-auth-required-sig")
  (ac c "Upstream -> Int" "S33-upstream-healthy-sig"))

(format t "~%=== E2E Results: ~D/~D PASSED ===~%" *pass* (+ *pass* *fail*))
(sb-ext:exit :code (if (zerop *fail*) 0 1))
