;;; migration-e2e-scenarios.lisp
(defun slurp (p) (with-open-file (in p) (let ((s (make-string (file-length in)))) (read-sequence s in) s)))
(defvar *pass* 0) (defvar *fail* 0)
(defun pass (n) (incf *pass*) (format t "  PASS ~A~%" n))
(defun fail (n r) (incf *fail*) (format t "  FAIL ~A: ~A~%" n r))
(defun ac (c needle s) (if (search needle c :test #'char=) (pass s) (fail s (format nil "missing ~S" needle))))
(let ((c (slurp "/home/slime/projects/clpkg-db-migration/src/core/migration-types.coal")))
  (ac c "module Core.MigrationTypes" "S1-module")
  (ac c "data MigrationDirection" "S2") (ac c "data MigrationStatus" "S3")
  (ac c "data MigrationStep" "S4") (ac c "data MigrationPlan" "S5")
  (ac c "data SchemaVersion" "S6") (ac c "data ColumnChange" "S7")
  (ac c "data TableChange" "S8") (ac c "data IndexChange" "S9")
  (ac c "data SchemaDiff" "S10") (ac c "data RollbackStrategy" "S11")
  (ac c "data MigrationConfig" "S12") (ac c "data MigrationLog" "S13")
  (ac c "data LockStatus" "S14") (ac c "data MigrationResult" "S15")
  (ac c "migration-pending-p" "S16") (ac c "plan-step-count" "S17")
  (ac c "diff-has-destructive" "S18") (ac c "version-newer-p" "S19")
  (ac c "Up" "S20-up") (ac c "Down" "S21-down")
  (ac c "Pending" "S22") (ac c "Applied" "S23") (ac c "RolledBack" "S24")
  (ac c "AddColumn" "S25") (ac c "DropColumn" "S26") (ac c "CreateTable" "S27")
  (ac c "DropTable" "S28") (ac c "CreateIndex" "S29") (ac c "AutoRollback" "S30")
  (ac c "Locked" "S31") (ac c "LockExpired" "S32")
  (ac c "MigrationStatus -> Bool" "S33") (ac c "SchemaDiff -> Bool" "S34")
  (ac c "SchemaVersion -> SchemaVersion -> Bool" "S35"))
(format t "~%=== E2E Results: ~D/~D PASSED ===~%" *pass* (+ *pass* *fail*))
(sb-ext:exit :code (if (zerop *fail*) 0 1))
