;;; encoder-e2e-scenarios.lisp — E2E for livestream encoder ADTs

(defun slurp (p) (with-open-file (in p) (let ((s (make-string (file-length in)))) (read-sequence s in) s)))
(defvar *pass* 0) (defvar *fail* 0)
(defun pass (n) (incf *pass*) (format t "  PASS ~A~%" n))
(defun fail (n r) (incf *fail*) (format t "  FAIL ~A: ~A~%" n r))
(defun ac (c needle s) (if (search needle c :test #'char=) (pass s) (fail s (format nil "missing ~S" needle))))

(let ((c (slurp "/home/slime/projects/clpkg-livestream-encoder/src/core/protocols.coal")))
  (ac c "module Core.Protocols" "S1-module")
  (ac c "data StreamProtocol" "S2-stream-protocol")
  (ac c "data Bitrate" "S3-bitrate")
  (ac c "data StreamConfig" "S4-stream-config")
  (ac c "data RtmpChunkType" "S5-rtmp-chunk-type")
  (ac c "data RtmpChunk" "S6-rtmp-chunk")
  (ac c "data RtmpHandshake" "S7-rtmp-handshake")
  (ac c "data HlsSegment" "S8-hls-segment")
  (ac c "data HlsPlaylistType" "S9-hls-playlist-type")
  (ac c "data HlsPlaylist" "S10-hls-playlist")
  (ac c "data FlvTagType" "S11-flv-tag-type")
  (ac c "data FlvTag" "S12-flv-tag")
  (ac c "data FlvHeader" "S13-flv-header")
  (ac c "data FrameResult" "S14-frame-result"))
(let ((c (slurp "/home/slime/projects/clpkg-livestream-encoder/src/core/rtmp-frames.coal")))
  (ac c "make-rtmp-chunk" "S15-make-rtmp-chunk")
  (ac c "make-handshake-c0" "S16-make-handshake-c0")
  (ac c "rtmp-chunk-header-size" "S17-rtmp-header-size")
  (ac c "serialize-rtmp-chunk" "S18-serialize-rtmp"))
(let ((c (slurp "/home/slime/projects/clpkg-livestream-encoder/src/core/hls-segments.coal")))
  (ac c "make-hls-segment" "S19-make-hls-segment")
  (ac c "make-hls-playlist" "S20-make-hls-playlist")
  (ac c "hls-segment-count" "S21-hls-segment-count")
  (ac c "serialize-hls-playlist" "S22-serialize-hls"))
(let ((c (slurp "/home/slime/projects/clpkg-livestream-encoder/src/core/flv-tags.coal")))
  (ac c "make-flv-header" "S23-make-flv-header")
  (ac c "make-flv-tag" "S24-make-flv-tag")
  (ac c "flv-tag-type-id" "S25-flv-tag-type-id")
  (ac c "serialize-flv-header" "S26-serialize-flv"))

(format t "~%=== E2E Results: ~D/~D PASSED ===~%" *pass* (+ *pass* *fail*))
(sb-ext:exit :code (if (zerop *fail*) 0 1))
