;;; backup-e2e-scenarios.lisp — E2E for backup/restore ADTs

(defun slurp (p) (with-open-file (in p) (let ((s (make-string (file-length in)))) (read-sequence s in) s)))
(defvar *pass* 0) (defvar *fail* 0)
(defun pass (n) (incf *pass*) (format t "  PASS ~A~%" n))
(defun fail (n r) (incf *fail*) (format t "  FAIL ~A: ~A~%" n r))
(defun ac (c needle s) (if (search needle c :test #'char=) (pass s) (fail s (format nil "missing ~S" needle))))

(let ((c (slurp "/home/slime/projects/clpkg-backup-restore/src/core/backup-types.coal")))
  (ac c "module Core.BackupTypes" "S1-module")
  (ac c "data BackupType" "S2-backup-type")
  (ac c "data CompressionAlg" "S3-compression-alg")
  (ac c "data StorageTargetType" "S4-storage-target-type")
  (ac c "data StorageTarget" "S5-storage-target")
  (ac c "data SnapshotStatus" "S6-snapshot-status")
  (ac c "data Snapshot" "S7-snapshot")
  (ac c "data RestoreStatus" "S8-restore-status")
  (ac c "data RestorePoint" "S9-restore-point")
  (ac c "data RetentionPolicy" "S10-retention-policy")
  (ac c "data ScheduleFreq" "S11-schedule-freq")
  (ac c "data BackupSchedule" "S12-backup-schedule")
  (ac c "data JobStatus" "S13-job-status")
  (ac c "data BackupJob" "S14-backup-job")
  (ac c "data BackupResult" "S15-backup-result")
  (ac c "snapshot-size-human" "S16-snapshot-size-human")
  (ac c "retention-expired-p" "S17-retention-expired-p")
  (ac c "job-succeeded-p" "S18-job-succeeded-p")
  (ac c "restore-complete-p" "S19-restore-complete-p")
  (ac c "FullBackup" "S20-full-backup")
  (ac c "IncrementalBackup" "S21-incremental-backup")
  (ac c "Zstd" "S22-zstd")
  (ac c "S3Compatible" "S23-s3-compatible")
  (ac c "SnapComplete" "S24-snap-complete")
  (ac c "SnapExpired" "S25-snap-expired")
  (ac c "RestoreVerifying" "S26-restore-verifying")
  (ac c "JobSucceeded" "S27-job-succeeded")
  (ac c "JobCancelled" "S28-job-cancelled")
  (ac c "Snapshot -> String" "S29-size-human-sig")
  (ac c "BackupJob -> Bool" "S30-job-succeeded-sig")
  (ac c "RestorePoint -> Bool" "S31-restore-complete-sig"))

(format t "~%=== E2E Results: ~D/~D PASSED ===~%" *pass* (+ *pass* *fail*))
(sb-ext:exit :code (if (zerop *fail*) 0 1))
