(load "packages/clpkg-shell-prompt-theme-manager/src/package.lisp")
(load "packages/clpkg-shell-prompt-theme-manager/src/model.lisp")
(load "packages/clpkg-shell-prompt-theme-manager/src/render.lisp")
(in-package #:clpkg-shell-prompt-theme-manager)
(defun %write-json (path json) (ensure-directories-exist path) (with-open-file (o path :direction :output :if-exists :supersede) (write-string json o)))
(defun %json-bool (x) (if x "true" "false"))
(let* ((sec "packages/clpkg-shell-prompt-theme-manager/artifacts/gates/security-gates.json")
       (perf "packages/clpkg-shell-prompt-theme-manager/artifacts/gates/perf-gates.json")
       (rel "packages/clpkg-shell-prompt-theme-manager/artifacts/gates/release-checks.json")
       (start (get-internal-real-time))
       (line (render-prompt-line (make-prompt-theme :left-format "<~A>" :right-format "{~A}" :separator " | ")
                                (make-prompt-context :cwd "/tmp" :branch "main")))
       (elapsed (* 1000.0d0 (/ (- (get-internal-real-time) start) internal-time-units-per-second)))
       (sec-ok (search "</tmp> | {main}" line))
       (perf-ok (< elapsed 50.0d0))
       (rel-ok (and (probe-file "packages/clpkg-shell-prompt-theme-manager/clpkg-shell-prompt-theme-manager.asd")
                    (probe-file "packages/clpkg-shell-prompt-theme-manager/e2e/run-s1-s6.sh"))))
  (%write-json sec (format nil "{\"render_ok\":~A,\"pass\":~A}" (%json-bool sec-ok) (%json-bool sec-ok)))
  (%write-json perf (format nil "{\"elapsed_ms\":~,3f,\"budget_ms\":50.0,\"pass\":~A}" elapsed (%json-bool perf-ok)))
  (%write-json rel (format nil "{\"asd_present\":~A,\"e2e_script_present\":~A,\"pass\":~A}"
                           (%json-bool (not (null (probe-file "packages/clpkg-shell-prompt-theme-manager/clpkg-shell-prompt-theme-manager.asd"))))
                           (%json-bool (not (null (probe-file "packages/clpkg-shell-prompt-theme-manager/e2e/run-s1-s6.sh"))))
                           (%json-bool rel-ok)))
  (unless (and sec-ok perf-ok rel-ok) (error "prompt gates failed"))
  (format t "PASS prompt-theme security/performance/release checks~%"))
