;;; subtitle-e2e-scenarios.lisp — E2E for subtitle editor ADTs

(defun slurp (p) (with-open-file (in p) (let ((s (make-string (file-length in)))) (read-sequence s in) s)))
(defvar *pass* 0) (defvar *fail* 0)
(defun pass (n) (incf *pass*) (format t "  PASS ~A~%" n))
(defun fail (n r) (incf *fail*) (format t "  FAIL ~A: ~A~%" n r))
(defun ac (c needle s) (if (search needle c :test #'char=) (pass s) (fail s (format nil "missing ~S" needle))))

(let ((c (slurp "/home/slime/projects/clpkg-subtitle-editor/src/core/formats.coal")))
  (ac c "module Core.Formats" "S1-module")
  (ac c "data Timestamp" "S2-timestamp")
  (ac c "data StyleTag" "S3-style-tag")
  (ac c "data CueStyle" "S4-cue-style")
  (ac c "data TimedCue" "S5-timed-cue")
  (ac c "data SubtitleFormat" "S6-subtitle-format")
  (ac c "data SrtEntry" "S7-srt-entry")
  (ac c "data VttHeader" "S8-vtt-header")
  (ac c "data VttCue" "S9-vtt-cue")
  (ac c "data AssStyle" "S10-ass-style")
  (ac c "data AssDialogue" "S11-ass-dialogue")
  (ac c "data AssScript" "S12-ass-script")
  (ac c "data ParseResult" "S13-parse-result"))
(let ((c (slurp "/home/slime/projects/clpkg-subtitle-editor/src/core/srt-parser.coal")))
  (ac c "parse-srt" "S14-parse-srt")
  (ac c "serialize-srt" "S15-serialize-srt")
  (ac c "srt-entry-count" "S16-srt-entry-count"))
(let ((c (slurp "/home/slime/projects/clpkg-subtitle-editor/src/core/vtt-parser.coal")))
  (ac c "parse-vtt" "S17-parse-vtt")
  (ac c "serialize-vtt" "S18-serialize-vtt")
  (ac c "vtt-cue-count" "S19-vtt-cue-count"))
(let ((c (slurp "/home/slime/projects/clpkg-subtitle-editor/src/core/ass-parser.coal")))
  (ac c "parse-ass" "S20-parse-ass")
  (ac c "serialize-ass" "S21-serialize-ass")
  (ac c "ass-dialogue-count" "S22-ass-dialogue-count"))

(format t "~%=== E2E Results: ~D/~D PASSED ===~%" *pass* (+ *pass* *fail*))
(sb-ext:exit :code (if (zerop *fail*) 0 1))
