(load "packages/clpkg-tui-file-manager/src/package.lisp")
(load "packages/clpkg-tui-file-manager/src/model.lisp")
(in-package #:clpkg-tui-file-manager)

(defun %write-json (path json)
  (ensure-directories-exist path)
  (with-open-file (o path :direction :output :if-exists :supersede)
    (write-string json o)))
(defun %json-bool (x) (if x "true" "false"))

(let* ((sec-path "packages/clpkg-tui-file-manager/artifacts/gates/security-gates.json")
       (perf-path "packages/clpkg-tui-file-manager/artifacts/gates/perf-gates.json")
       (rel-path "packages/clpkg-tui-file-manager/artifacts/gates/release-checks.json")
       (start (get-internal-real-time))
       (entry-a (make-file-entry :path "a.txt" :kind :file :size-bytes 10 :modified-at 1))
       (entry-z (make-file-entry :path "z.txt" :kind :file :size-bytes 20 :modified-at 2))
       (state (make-file-state :cwd "/tmp"
                               :entries (list entry-z entry-a)
                               :selection (make-selection-state :cursor-path "z.txt" :marked-paths '("a.txt"))))
       (next (apply-navigation-event state "a.txt"))
       (sorted-paths (mapcar #'fe-path (fs-entries next)))
       (elapsed-ms (* 1000.0d0 (/ (- (get-internal-real-time) start) internal-time-units-per-second)))
       (sec-ok (and (equal sorted-paths '("a.txt" "z.txt"))
                    (string= (ss-cursor-path (fs-selection next)) "a.txt")))
       (perf-ok (< elapsed-ms 80.0d0))
       (release-ok (and (probe-file "packages/clpkg-tui-file-manager/clpkg-tui-file-manager.asd")
                        (probe-file "packages/clpkg-tui-file-manager/e2e/run-s1-s6.sh"))))
  (%write-json sec-path (format nil "{\"deterministic_sort\":~A,\"cursor_update\":~A,\"pass\":~A}"
                                (%json-bool (equal sorted-paths '("a.txt" "z.txt")))
                                (%json-bool (string= (ss-cursor-path (fs-selection next)) "a.txt"))
                                (%json-bool sec-ok)))
  (%write-json perf-path (format nil "{\"elapsed_ms\":~,3f,\"budget_ms\":80.0,\"pass\":~A}" elapsed-ms (%json-bool perf-ok)))
  (%write-json rel-path (format nil "{\"asd_present\":~A,\"e2e_script_present\":~A,\"pass\":~A}"
                                (%json-bool (not (null (probe-file "packages/clpkg-tui-file-manager/clpkg-tui-file-manager.asd"))))
                                (%json-bool (not (null (probe-file "packages/clpkg-tui-file-manager/e2e/run-s1-s6.sh"))))
                                (%json-bool release-ok)))
  (unless (and sec-ok perf-ok release-ok)
    (error "file-manager security/perf/release gate failed"))
  (format t "PASS file-manager security/performance/release checks~%"))
