(defun slurp (p) (with-open-file (in p) (let ((s (make-string (file-length in)))) (read-sequence s in) s)))
(defvar *pass* 0) (defvar *fail* 0)
(defun pass (n) (incf *pass*) (format t "  PASS ~A~%" n))
(defun fail (n r) (incf *fail*) (format t "  FAIL ~A: ~A~%" n r))
(defun ac (c needle s) (if (search needle c :test #'char=) (pass s) (fail s (format nil "missing ~S" needle))))
(let ((c (slurp "/home/slime/projects/clpkg-incident-response/src/core/incident-types.coal")))
  (ac c "module Core.IncidentTypes" "S1") (ac c "data Severity" "S2")
  (ac c "data IncidentStatus" "S3") (ac c "data Incident" "S4")
  (ac c "data TimelineEntry" "S5") (ac c "data TimelineAction" "S6")
  (ac c "data EscalationLevel" "S7") (ac c "data EscalationPolicy" "S8")
  (ac c "data Responder" "S9") (ac c "data ResponderRole" "S10")
  (ac c "data Evidence" "S11") (ac c "data EvidenceType" "S12")
  (ac c "data Playbook" "S13") (ac c "data PostMortem" "S14")
  (ac c "data IncidentResult" "S15") (ac c "incident-open-p" "S16")
  (ac c "incident-age-hours" "S17") (ac c "escalation-needed-p" "S18")
  (ac c "evidence-count" "S19") (ac c "Critical" "S20") (ac c "Detected" "S21")
  (ac c "Contained" "S22") (ac c "Eradicated" "S23") (ac c "Recovered" "S24")
  (ac c "L1" "S25") (ac c "Executive" "S26") (ac c "Coordinator" "S27")
  (ac c "LogFile" "S28") (ac c "MemoryDump" "S29")
  (ac c "IncidentStatus -> Bool" "S30") (ac c "EscalationPolicy -> Int -> Bool" "S31"))
(format t "~%=== E2E Results: ~D/~D PASSED ===~%" *pass* (+ *pass* *fail*))
(sb-ext:exit :code (if (zerop *fail*) 0 1))
