;;; query-e2e-scenarios.lisp — E2E for query IDE ADTs

(defun slurp (p) (with-open-file (in p) (let ((s (make-string (file-length in)))) (read-sequence s in) s)))
(defvar *pass* 0) (defvar *fail* 0)
(defun pass (n) (incf *pass*) (format t "  PASS ~A~%" n))
(defun fail (n r) (incf *fail*) (format t "  FAIL ~A: ~A~%" n r))
(defun ac (c needle s) (if (search needle c :test #'char=) (pass s) (fail s (format nil "missing ~S" needle))))

(let ((c (slurp "/home/slime/projects/clpkg-query-ide/src/core/query-types.coal")))
  (ac c "module Core.QueryTypes" "S1-module")
  (ac c "data ColumnType" "S2-column-type")
  (ac c "data ColumnDef" "S3-column-def")
  (ac c "data ResultSet" "S4-result-set")
  (ac c "data QueryLanguage" "S5-query-language")
  (ac c "data Query" "S6-query")
  (ac c "data QueryStatus" "S7-query-status")
  (ac c "data ConnectionDriver" "S8-connection-driver")
  (ac c "data Connection" "S9-connection")
  (ac c "data SchemaObject" "S10-schema-object")
  (ac c "data SchemaInfo" "S11-schema-info")
  (ac c "data PlanNode" "S12-plan-node")
  (ac c "data ExecutionPlan" "S13-execution-plan")
  (ac c "data HistoryEntry" "S14-history-entry")
  (ac c "data QueryResult" "S15-query-result")
  (ac c "resultset-row-count" "S16-resultset-row-count")
  (ac c "query-is-readonly" "S17-query-is-readonly")
  (ac c "connection-active-p" "S18-connection-active-p")
  (ac c "plan-estimated-cost" "S19-plan-estimated-cost")
  (ac c "ColInteger" "S20-col-integer")
  (ac c "ColTimestamp" "S21-col-timestamp")
  (ac c "ColJson" "S22-col-json")
  (ac c "SPARQL" "S23-sparql")
  (ac c "Cypher" "S24-cypher")
  (ac c "PostgreSQL" "S25-postgresql")
  (ac c "SQLite" "S26-sqlite")
  (ac c "TableObj" "S27-table-obj")
  (ac c "ViewObj" "S28-view-obj")
  (ac c "IndexObj" "S29-index-obj")
  (ac c "ResultSet -> Int" "S30-row-count-sig")
  (ac c "Query -> Bool" "S31-readonly-sig")
  (ac c "Connection -> Bool" "S32-active-p-sig")
  (ac c "ExecutionPlan -> Double" "S33-plan-cost-sig"))

(format t "~%=== E2E Results: ~D/~D PASSED ===~%" *pass* (+ *pass* *fail*))
(sb-ext:exit :code (if (zerop *fail*) 0 1))
