;;; mesh-e2e-scenarios.lisp — E2E for service mesh ADTs

(defun slurp (p) (with-open-file (in p) (let ((s (make-string (file-length in)))) (read-sequence s in) s)))
(defvar *pass* 0) (defvar *fail* 0)
(defun pass (n) (incf *pass*) (format t "  PASS ~A~%" n))
(defun fail (n r) (incf *fail*) (format t "  FAIL ~A: ~A~%" n r))
(defun ac (c needle s) (if (search needle c :test #'char=) (pass s) (fail s (format nil "missing ~S" needle))))

(let ((c (slurp "/home/slime/projects/clpkg-service-mesh/src/core/mesh-types.coal")))
  (ac c "module Core.MeshTypes" "S1-module")
  (ac c "data Protocol" "S2-protocol")
  (ac c "data ServiceEndpoint" "S3-service-endpoint")
  (ac c "data HealthCheckType" "S4-health-check-type")
  (ac c "data HealthCheckPolicy" "S5-health-check-policy")
  (ac c "data LoadBalancerPolicy" "S6-load-balancer-policy")
  (ac c "data CircuitBreakerState" "S7-circuit-breaker-state")
  (ac c "data CircuitBreakerConfig" "S8-circuit-breaker-config")
  (ac c "data RetryBackoff" "S9-retry-backoff")
  (ac c "data RetryPolicy" "S10-retry-policy")
  (ac c "data MtlsMode" "S11-mtls-mode")
  (ac c "data MtlsConfig" "S12-mtls-config")
  (ac c "data ProxySidecar" "S13-proxy-sidecar")
  (ac c "data ProxyConfig" "S14-proxy-config")
  (ac c "data TrafficPolicy" "S15-traffic-policy")
  (ac c "data MeshResult" "S16-mesh-result")
  (ac c "endpoint-healthy-p" "S17-endpoint-healthy-p")
  (ac c "circuit-open-p" "S18-circuit-open-p")
  (ac c "max-retries" "S19-max-retries")
  (ac c "mtls-enabled-p" "S20-mtls-enabled-p")
  (ac c "RoundRobin" "S21-round-robin")
  (ac c "LeastConnections" "S22-least-connections")
  (ac c "ConsistentHash" "S23-consistent-hash")
  (ac c "Closed" "S24-cb-closed")
  (ac c "HalfOpen" "S25-cb-half-open")
  (ac c "Strict" "S26-mtls-strict")
  (ac c "Permissive" "S27-mtls-permissive")
  (ac c "ExponentialBackoff" "S28-exponential-backoff")
  (ac c "HttpHealthCheck" "S29-http-health-check")
  (ac c "ServiceEndpoint -> Bool" "S30-endpoint-healthy-sig")
  (ac c "CircuitBreakerState -> Bool" "S31-circuit-open-sig")
  (ac c "RetryPolicy -> Int" "S32-max-retries-sig")
  (ac c "MtlsConfig -> Bool" "S33-mtls-enabled-sig"))

(format t "~%=== E2E Results: ~D/~D PASSED ===~%" *pass* (+ *pass* *fail*))
(sb-ext:exit :code (if (zerop *fail*) 0 1))
