(load "/home/slime/projects/clpkg/packages/clpkg-voice-notes-app/src/pipeline/pipeline-stubs.lisp")
(load "/home/slime/projects/clpkg/packages/clpkg-voice-notes-app/src/security/path-safety.lisp")

(defun assert-true (x msg) (unless x (error "~A" msg)))

(let* ((path "/var/voice-notes/inbox/sample.wav"))
  (assert-true (clpkg-voice-notes-app.security:safe-media-path-p path) "safe path rejected")
  (let* ((ingest (clpkg-voice-notes-app.pipeline:ingest-note path))
         (transcribe (clpkg-voice-notes-app.pipeline:transcribe-note (cdr ingest)))
         (validate (clpkg-voice-notes-app.pipeline:validate-note (cdr transcribe)))
         (index (clpkg-voice-notes-app.pipeline:index-note (cdr validate)))
         (emit (clpkg-voice-notes-app.pipeline:emit-note (cdr index))))
    (assert-true (eq :ok (car ingest)) "ingest failed")
    (assert-true (eq :ok (car transcribe)) "transcribe failed")
    (assert-true (eq :ok (car validate)) "validate failed")
    (assert-true (eq :ok (car index)) "index failed")
    (assert-true (eq :ok (car emit)) "emit failed")
    (format t "=== E2E PASSED ===~%")
    (sb-ext:exit :code 0)))
