(defun slurp (p) (with-open-file (in p) (let ((s (make-string (file-length in)))) (read-sequence s in) s)))
(defvar *p* 0) (defvar *f* 0)
(defun p (n) (incf *p*) (format t "  PASS ~A~%" n))
(defun f (n r) (incf *f*) (format t "  FAIL ~A: ~A~%" n r))
(defun a (c n s) (if (search n c :test #'char=) (p s) (f s (format nil "~S" n))))
(let ((c (slurp "/home/slime/projects/clpkg-endpoint-protection/src/core/epp-types.coal")))
  (a c "module Core.EppTypes" "S1") (a c "data ThreatType" "S2")
  (a c "data ThreatSeverity" "S3") (a c "data Detection" "S4")
  (a c "data DetectionAction" "S5") (a c "data ScanType" "S6")
  (a c "data ScanSchedule" "S7") (a c "data QuarantineEntry" "S8")
  (a c "data ExclusionRule" "S9") (a c "data ExclusionType" "S10")
  (a c "data PolicyEnforcement" "S11") (a c "data DeviceStatus" "S12")
  (a c "data AgentHealth" "S13") (a c "data ThreatIntel" "S14")
  (a c "data EppResult" "S15") (a c "detection-is-malware" "S16")
  (a c "quarantine-age-hours" "S17") (a c "agent-healthy-p" "S18")
  (a c "threat-score-high-p" "S19") (a c "Malware" "S20")
  (a c "Ransomware" "S21") (a c "Rootkit" "S22") (a c "Quarantined" "S23")
  (a c "FullScan" "S24") (a c "QuickScan" "S25") (a c "Enforce" "S26")
  (a c "DeviceProtected" "S27") (a c "Detection -> Bool" "S28")
  (a c "AgentHealth -> Bool" "S29") (a c "ThreatIntel -> Bool" "S30"))
(format t "~%=== E2E: ~D/~D PASSED ===~%" *p* (+ *p* *f*))
(sb-ext:exit :code (if (zerop *f*) 0 1))
