(in-package #:clpkg-outliner)

(define-condition outline-error (error) ())
(define-condition outline-parse-error (outline-error)
  ((reason :initarg :reason :reader reason))
  (:report (lambda (c s) (format s "Parse error: ~a" (reason c)))))
(define-condition outline-invariant-error (outline-error)
  ((reason :initarg :reason :reader reason))
  (:report (lambda (c s) (format s "Invariant error: ~a" (reason c)))))

(defstruct (node (:constructor make-node (id parent title &optional (body ""))))
  (id 0 :type fixnum)
  (parent nil :type (or null fixnum))
  (children '() :type list)
  (title "" :type string)
  (body "" :type string))

(defstruct (document (:constructor %make-document))
  (version 1 :type fixnum)
  (nodes (make-hash-table :test #'eql) :type hash-table))

(defun make-empty-document ()
  (let ((doc (%make-document)))
    (setf (gethash 0 (document-nodes doc)) (make-node 0 nil "root" ""))
    doc))

(defun %require-node (doc id)
  (or (gethash id (document-nodes doc))
      (error 'outline-invariant-error :reason (format nil "Missing node ~a" id))))

(defun insert-node (doc parent-id node-id title &optional (body ""))
  (declare (type fixnum parent-id node-id) (type string title body))
  (when (gethash node-id (document-nodes doc))
    (error 'outline-invariant-error :reason (format nil "Duplicate node id ~a" node-id)))
  (let ((parent (%require-node doc parent-id))
        (node (make-node node-id parent-id title body)))
    (push node-id (node-children parent))
    (setf (gethash node-id (document-nodes doc)) node)
    doc))

(defun check-invariants (doc)
  (let ((nodes (document-nodes doc))
        (seen-parents (make-hash-table :test #'eql)))
    (maphash
     (lambda (id n)
       (declare (ignore id))
       (let ((p (node-parent n)))
         (when p
           (unless (gethash p nodes)
             (error 'outline-invariant-error :reason (format nil "Parent ~a missing for node ~a" p (node-id n))))
           (incf (gethash (node-id n) seen-parents 0)))))
     nodes)
    ;; each child listed by parent should point back to that parent
    (maphash
     (lambda (id n)
       (dolist (cid (node-children n))
         (let ((child (%require-node doc cid)))
           (unless (eql (node-parent child) id)
             (error 'outline-invariant-error
                    :reason (format nil "Child ~a parent mismatch expected ~a got ~a" cid id (node-parent child)))))))
     nodes)
    ;; cycle check via DFS
    (labels ((dfs (id visiting visited)
               (when (gethash id visiting)
                 (error 'outline-invariant-error :reason (format nil "Cycle at ~a" id)))
               (unless (gethash id visited)
                 (setf (gethash id visiting) t)
                 (dolist (cid (node-children (%require-node doc id)))
                   (dfs cid visiting visited))
                 (remhash id visiting)
                 (setf (gethash id visited) t))))
      (dfs 0 (make-hash-table :test #'eql) (make-hash-table :test #'eql)))
    t))

(defun document->sexp (doc)
  (let ((acc '()))
    (maphash (lambda (_id n)
               (push (list :id (node-id n)
                           :parent (node-parent n)
                           :children (reverse (copy-list (node-children n)))
                           :title (node-title n)
                           :body (node-body n))
                     acc))
             (document-nodes doc))
    (list :version (document-version doc) :nodes (sort acc #'< :key (lambda (x) (getf x :id))))))

(defun sexp->document (sexp)
  (handler-case
      (let* ((version (getf sexp :version))
             (rows (getf sexp :nodes))
             (doc (%make-document)))
        (setf (document-version doc) version)
        (dolist (row rows)
          (let* ((id (getf row :id))
                 (parent (getf row :parent))
                 (title (or (getf row :title) ""))
                 (body (or (getf row :body) ""))
                 (children (or (getf row :children) '()))
                 (n (make-node id parent title body)))
            (setf (node-children n) children)
            (setf (gethash id (document-nodes doc)) n)))
        (check-invariants doc)
        doc)
    (error (e)
      (error 'outline-parse-error :reason (princ-to-string e)))))

(defun save-document (doc path)
  (with-open-file (out path :direction :output :if-exists :supersede :if-does-not-exist :create)
    (let ((*print-circle* t)
          (*print-pretty* t))
      (prin1 (document->sexp doc) out)
      (terpri out)))
  path)

(defun load-document (path)
  (with-open-file (in path :direction :input)
    (sexp->document (read in nil nil))))
