(in-package #:clpkg-serial-console-client)

(deftype serial-connection-state () '(member :new :opening :open :closing :closed :error))

(defstruct (serial-port-profile (:conc-name spp-))
  (device-path "" :type string)
  (baud-rate 115200 :type integer)
  (data-bits 8 :type integer)
  (parity :none :type keyword)
  (stop-bits 1 :type integer)
  (flow-control :none :type keyword))

(defstruct (serial-session (:conc-name ss-))
  (session-id "" :type string)
  (state :new :type serial-connection-state)
  (port (make-serial-port-profile) :type serial-port-profile)
  (bytes-rx 0 :type integer)
  (bytes-tx 0 :type integer)
  (last-error "" :type string))

(defun build-serial-session-summary (session)
  (declare (type serial-session session)
           (optimize (safety 3)))
  (list :session-id (ss-session-id session)
        :state (ss-state session)
        :device (spp-device-path (ss-port session))
        :baud (spp-baud-rate (ss-port session))
        :parity (spp-parity (ss-port session))
        :flow-control (spp-flow-control (ss-port session))))
