(in-package #:clpkg-tui-git-client)

(defstruct (repo-status (:conc-name rs-))
  (repo-path "" :type string)
  (head "" :type string)
  (dirty-p nil :type boolean)
  (staged-count 0 :type integer)
  (unstaged-count 0 :type integer)
  (untracked-count 0 :type integer))

(defstruct (branch-state (:conc-name bs-))
  (name "" :type string)
  (upstream "" :type string)
  (ahead 0 :type integer)
  (behind 0 :type integer))

(defstruct (diff-stat (:conc-name ds-))
  (files-changed 0 :type integer)
  (insertions 0 :type integer)
  (deletions 0 :type integer))

(defun build-status-view (status branch diff)
  (declare (type repo-status status)
           (type branch-state branch)
           (type diff-stat diff)
           (optimize (safety 3)))
  (list :repo (rs-repo-path status)
        :head (rs-head status)
        :dirty (rs-dirty-p status)
        :branch (bs-name branch)
        :ahead (bs-ahead branch)
        :behind (bs-behind branch)
        :changed (ds-files-changed diff)
        :insertions (ds-insertions diff)
        :deletions (ds-deletions diff)))
