(load "packages/clpkg-tui-git-client/src/package.lisp")
(load "packages/clpkg-tui-git-client/src/model.lisp")
(in-package #:clpkg-tui-git-client)

(defun %write-json (path json)
  (ensure-directories-exist path)
  (with-open-file (o path :direction :output :if-exists :supersede)
    (write-string json o)))
(defun %json-bool (x) (if x "true" "false"))

(let* ((sec-path "packages/clpkg-tui-git-client/artifacts/gates/security-gates.json")
       (perf-path "packages/clpkg-tui-git-client/artifacts/gates/perf-gates.json")
       (rel-path "packages/clpkg-tui-git-client/artifacts/gates/release-checks.json")
       (start (get-internal-real-time))
       (view (build-status-view
              (make-repo-status :repo-path "/tmp/repo" :head "abc" :dirty-p t :staged-count 1 :unstaged-count 2 :untracked-count 0)
              (make-branch-state :name "main" :upstream "origin/main" :ahead 1 :behind 0)
              (make-diff-stat :files-changed 3 :insertions 10 :deletions 4)))
       (elapsed-ms (* 1000.0d0 (/ (- (get-internal-real-time) start) internal-time-units-per-second)))
       (sec-ok (and (stringp (getf view :repo)) (stringp (getf view :head))))
       (perf-ok (< elapsed-ms 80.0d0))
       (release-ok (and (probe-file "packages/clpkg-tui-git-client/clpkg-tui-git-client.asd")
                        (probe-file "packages/clpkg-tui-git-client/e2e/run-s1-s6.sh"))))
  (%write-json sec-path (format nil "{\"typed_view\":~A,\"pass\":~A}" (%json-bool sec-ok) (%json-bool sec-ok)))
  (%write-json perf-path (format nil "{\"elapsed_ms\":~,3f,\"budget_ms\":80.0,\"pass\":~A}" elapsed-ms (%json-bool perf-ok)))
  (%write-json rel-path (format nil "{\"asd_present\":~A,\"e2e_script_present\":~A,\"pass\":~A}"
                                (%json-bool (not (null (probe-file "packages/clpkg-tui-git-client/clpkg-tui-git-client.asd"))))
                                (%json-bool (not (null (probe-file "packages/clpkg-tui-git-client/e2e/run-s1-s6.sh"))))
                                (%json-bool release-ok)))
  (unless (and sec-ok perf-ok release-ok)
    (error "git-client security/perf/release gate failed"))
  (format t "PASS git-client security/performance/release checks~%"))
