(defun slurp (p) (with-open-file (in p) (let ((s (make-string (file-length in)))) (read-sequence s in) s)))
(defvar *pass* 0) (defvar *fail* 0)
(defun pass (n) (incf *pass*) (format t "  PASS ~A~%" n))
(defun fail (n r) (incf *fail*) (format t "  FAIL ~A: ~A~%" n r))
(defun ac (c needle s) (if (search needle c :test #'char=) (pass s) (fail s (format nil "missing ~S" needle))))
(let ((c (slurp "/home/slime/projects/clpkg-rdbms/src/core/rdbms-types.coal")))
  (ac c "module Core.RdbmsTypes" "S1") (ac c "data SqlType" "S2")
  (ac c "data ColumnConstraint" "S3") (ac c "data ColumnDef" "S4")
  (ac c "data TableDef" "S5") (ac c "data ForeignKey" "S6")
  (ac c "data IndexDef" "S7") (ac c "data SqlValue" "S8")
  (ac c "data Row" "S9") (ac c "data ResultSet" "S10")
  (ac c "data TransactionIsolation" "S11") (ac c "data Transaction" "S12")
  (ac c "data QueryPlan" "S13") (ac c "data PlanNodeType" "S14")
  (ac c "data RdbmsResult" "S15") (ac c "column-nullable-p" "S16")
  (ac c "resultset-empty-p" "S17") (ac c "table-column-count" "S18")
  (ac c "plan-estimated-rows" "S19") (ac c "SqlInteger" "S20")
  (ac c "SqlVarchar" "S21") (ac c "SqlTimestamp" "S22") (ac c "SqlJson" "S23")
  (ac c "NotNull" "S24") (ac c "PrimaryKey" "S25") (ac c "DefaultValue" "S26")
  (ac c "References" "S27") (ac c "ValInt" "S28") (ac c "ValNull" "S29")
  (ac c "ReadUncommitted" "S30") (ac c "Serializable" "S31")
  (ac c "SeqScan" "S32") (ac c "IndexScan" "S33") (ac c "HashJoin" "S34")
  (ac c "MergeJoin" "S35") (ac c "ColumnDef -> Bool" "S36")
  (ac c "ResultSet -> Bool" "S37") (ac c "QueryPlan -> Double" "S38"))
(format t "~%=== E2E Results: ~D/~D PASSED ===~%" *pass* (+ *pass* *fail*))
(sb-ext:exit :code (if (zerop *fail*) 0 1))
