;;; secret-e2e-scenarios.lisp — E2E scenario tests for secret manager ADTs

(defun slurp (p) (with-open-file (in p) (let ((s (make-string (file-length in)))) (read-sequence s in) s)))
(defvar *pass* 0) (defvar *fail* 0)
(defun pass (n) (incf *pass*) (format t "  PASS ~A~%" n))
(defun fail (n r) (incf *fail*) (format t "  FAIL ~A: ~A~%" n r))
(defun ac (c needle s) (if (search needle c :test #'char=) (pass s) (fail s (format nil "missing ~S" needle))))

(let ((c (slurp "/home/slime/projects/clpkg-secret-manager/src/core/secret-types.coal")))
  (ac c "module Core.SecretTypes" "S1-module")
  (ac c "data EncryptionAlgorithm" "S2-encryption-algorithm")
  (ac c "data SecretVersion" "S3-secret-version")
  (ac c "data SecretEntry" "S4-secret-entry")
  (ac c "data SecretMetadata" "S5-secret-metadata")
  (ac c "data VaultBackendType" "S6-vault-backend-type")
  (ac c "data VaultBackend" "S7-vault-backend")
  (ac c "data AccessLevel" "S8-access-level")
  (ac c "data AccessPolicy" "S9-access-policy")
  (ac c "data RotationFrequency" "S10-rotation-frequency")
  (ac c "data RotationSchedule" "S11-rotation-schedule")
  (ac c "data AuditAction" "S12-audit-action")
  (ac c "data AuditEvent" "S13-audit-event")
  (ac c "data SecretResult" "S14-secret-result")
  (ac c "secret-is-active" "S15-secret-is-active")
  (ac c "secret-age-days" "S16-secret-age-days")
  (ac c "rotation-due-p" "S17-rotation-due-p")
  (ac c "access-permitted-p" "S18-access-permitted-p")
  (ac c "AES256GCM" "S19-aes256gcm")
  (ac c "ChaCha20Poly1305" "S20-chacha20")
  (ac c "ReadSecret" "S21-read-secret")
  (ac c "AdminSecret" "S22-admin-secret")
  (ac c "RotateDaily" "S23-rotate-daily")
  (ac c "AuditRead" "S24-audit-read")
  (ac c "AuditRotate" "S25-audit-rotate")
  (ac c "FileBackend" "S26-file-backend")
  (ac c "SecretEntry -> Bool" "S27-is-active-sig")
  (ac c "RotationSchedule -> Int -> Bool" "S28-rotation-due-sig")
  (ac c "AccessPolicy -> AccessLevel -> String -> Bool" "S29-access-permitted-sig"))

(format t "~%=== E2E Results: ~D/~D PASSED ===~%" *pass* (+ *pass* *fail*))
(sb-ext:exit :code (if (zerop *fail*) 0 1))
