(load "packages/clpkg-clipboard-history/src/package.lisp")
(load "packages/clpkg-clipboard-history/src/model.lisp")
(load "packages/clpkg-clipboard-history/src/store.lisp")
(in-package #:clpkg-clipboard-history)

(let* ((s (make-clipboard-store :limit 2 :entries '()))
       (e1 (make-clipboard-entry :entry-id "1" :text "alpha" :created-at 1 :content-hash 11))
       (e2 (make-clipboard-entry :entry-id "2" :text "beta" :created-at 2 :content-hash 22))
       (e3 (make-clipboard-entry :entry-id "3" :text "alpha+gamma" :created-at 3 :content-hash 33))
       (s1 (append-entry s e1))
       (s2 (append-entry s1 e2))
       (s3 (append-entry s2 e3))
       (all (store->newest-first s3))
       (q (query-substring s3 "alpha")))
  (unless (and (= (length (cs-entries s3)) 2)
               (string= (ce-entry-id (first all)) "3")
               (= (length q) 1)
               (string= (ce-entry-id (first q)) "3"))
    (error "clipboard-store MVP verification failed"))
  (format t "PASS clipboard-history bounded-retention MVP~%"))
